language: node_js
node_js:
  - '10'
install:
  - yarn
cache:
  yarn: true
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
stages:
  - lint&test
  - build&deploy
jobs:
  include:
    - stage: lint&test
      script:
        - npm run lint:es
        - npm run lint:style
        - npm run test -- -w=2 --testPathIgnorePatterns=image.test.js
    - stage: build&deploy
      script:
        - npm run build:dist
        - npm run build:lib
        - npm run build:ts
        - npm run build:gh-pages
        - npx jest tests/lib.manual.test.js
      deploy:
        - provider: releases
          skip_cleanup: true
          api_key:
            secure: AZmdbAGXGEk1Qi3YpqOmUZRQK3/nnNeSo96bbXzAtMBlb4osWG7Bm1iasjMXITIOXc/fNNf1L0lkfn+naVPHicfg2ZEt/ABGO9vQPXSuhio+ss2SpCkQ5PWxGIB5wXbjC3jXfsKitDQ/wyxAcF8LoWif8VIEYZpd03vik20mBMJKgcBbH5i1+2PV6CkybjhJ4HC2YePb3/LJqBRwBxMnn7lPVd9LAB3a5GmqWLkbmdWpplWSANX1jJz5AvxmznqWbSYV8gn25q2hmuc9knb4vwC/Bz9a70O+MnAC5fgLLozmq67kyjTd96txLQLnY0lXD+z1m+5Bukh3LxiKz9RYMTW32Mip4+iN0B1953Zb5jUoLD/TXrN4DUcPJatpUx7A3Ub4VFYXZnNj3xJOw62VwclNqQIpodUpFYQs//4uPpEPq8JTy9iQ5RsYOcEbVbphT3Hmq3dG/68Q509yVCrIgINcBgkOvT/vT0z9aZWoHd+7zjoZyLkzn62CGf1QZiYDqkoGLKz/bkCo8aXhWPe3UmioYZPTsEl9txmkLHwMeB3WjEB9/xIUVA6VG2QOq9pzy8aPxY2q6LVy2e6uWnEU85IONDAhmMx1bs+Ja/rK1eo3kvYgEKk7/w4oeF+CA/41ZHUUOeLqqinekVBWO4VBFWEJwASzIwAt9mt7brDCUGg=
          file_glob: true
          file: dist/*
          on:
            tags: true
            repo: UCloud-FE/react-components
            branch: master
