# Javascript Node CircleCI 2.0 configuration file
version: 2

references:
  container_config: &container_config
    docker:
      - image: circleci/node:10
    working_directory: ~/react-components
  attach_workspace: &attach_workspace
    attach_workspace:
      at: ~/react-components

jobs:
  setup:
    <<: *container_config
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - yarn-packages-v1.0-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1.0-{{ .Branch }}-
            - yarn-packages-v1.0-
      - run: yarn install
      - save_cache:
          paths:
            - ~/.cache/yarn
            - node_modules
          key: yarn-packages-v1.0-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: ~/react-components
          paths:
            - node_modules

  end:
    <<: *container_config
    steps:
      - run: echo end

  eslint:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run: npm run lint:es
  stylelint:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run: npm run lint:style
  test:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run: npm run test -- -w=2 --collectCoverage --testPathIgnorePatterns=image.test.js
      - persist_to_workspace:
          root: ~/react-components
          paths:
            - coverage

  codecov:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run: sudo npm install -g codecov
      - run: codecov

  build dist:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run: npm run build:dist
      - persist_to_workspace:
          root: ~/react-components
          paths:
            - dist
  build lib:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run: npm run build:lib
      - run: npm run build:ts
      - persist_to_workspace:
          root: ~/react-components
          paths:
            - lib
  build gh-pages:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run: npm run build:gh-pages

  test lib:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run: npx jest tests/lib.manual.test.js

  deploy npm:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/react-components/.npmrc
      - run:
          name: Publish package
          command: npm publish

  deploy pages:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run:
          name: publish to github pages
          command: npm run deploy:gh-pages

workflows:
  version: 2
  test-and-build-and-deploy:
    jobs:
      - setup:
          filters:
            branches:
              ignore: gh-pages
      - eslint:
          requires:
            - setup
      - stylelint:
          requires:
            - setup
      - test:
          requires:
            - eslint
            - stylelint
      - codecov:
          requires:
            - test
      - build dist:
          requires:
            - test
      - build lib:
          requires:
            - test
      - build gh-pages:
          requires:
            - test
      - test lib:
          requires:
            - build dist
            - build lib
      - deploy npm:
          requires:
            - test
            - build dist
            - build lib
            - build gh-pages
            - test lib
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - deploy pages:
          requires:
            - deploy npm
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - end:
          requires:
            - test
            - build dist
            - build lib
            - build gh-pages
            - test lib
            - deploy npm
            - deploy pages
